name: tonefinish
base: core22
version: "1.0.3"
summary: Audio finisher con analisis y normalizacion
description: |
  ToneFinish es una aplicacion de audio para analizar, normalizar y finalizar audio.

grade: stable
confinement: classic

apps:
  tonefinish:
    command: bin/tonefinish

parts:
  tonefinish:
    plugin: dump
    source: ../..
    stage-packages:
      - python3
      - python3-venv
      - python3-pip
      - ffmpeg
    organize:
      audio_analysis.py: usr/lib/tonefinish/audio_analysis.py
      audio_processing.py: usr/lib/tonefinish/audio_processing.py
      audio_tools.py: usr/lib/tonefinish/audio_tools.py
      config.py: usr/lib/tonefinish/config.py
      ui_app.py: usr/lib/tonefinish/ui_app.py
      main.py: usr/lib/tonefinish/main.py
      normalize_audio.py: usr/lib/tonefinish/normalize_audio.py
      requirements.txt: usr/lib/tonefinish/requirements.txt
      VERSION: usr/lib/tonefinish/VERSION
      README.md: usr/lib/tonefinish/README.md
    override-build: |
      craftctl default
      cat > $SNAPCRAFT_PART_INSTALL/bin/tonefinish <<'EOF'
      #!/usr/bin/env bash
      set -e
      BASE_DIR="$SNAP/usr/lib/tonefinish"
      VENV_DIR="$SNAP_USER_COMMON/venv"
      if [ ! -d "$VENV_DIR" ]; then
        python3 -m venv "$VENV_DIR"
        "$VENV_DIR/bin/pip" install -r "$BASE_DIR/requirements.txt"
      fi
      exec "$VENV_DIR/bin/python" "$BASE_DIR/main.py"
      EOF
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/tonefinish
